version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order
    ports:
      - "5433:5432"
  order-service:
    #image: vitjanz/rso-projekt:customers-api-rso
    image: orders-api-test
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/order
    ports:
      - "8081:8081"
    depends_on:
      - postgres