kumuluzee:
  name: playlists-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://*:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/PlaylistsDS
      connection-url: jdbc:postgresql://172.17.0.1:5433/playlist
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
      etcd:
        hosts: http://192.168.99.100:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/PlaylistsDS
  discovery:
      etcd:
        hosts: http://localhost:2379
      ttl: 20
      ping-interval: 15
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="playlists">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="45accb08-87ef-4735-9cb4-2eb70f46f38e-ls.logit.io" port="14826"
                                                                                         protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="ERROR"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'