language: java
jdk: oraclejdk8
install: true
script:
  - mvn clean package
  - docker build -t $DOCKER_USERNAME/rso-projekt:customers-api-rso ./customers/
  - docker build -t $DOCKER_USERNAME/rso-projekt:orders-api-rso ./orders/
  - docker build -t $DOCKER_USERNAME/rso-projekt:video-api-rso ./video/
  - docker build -t $DOCKER_USERNAME/rso-projekt:playlists-api-rso ./playlists/
  - docker build -t $DOCKER_USERNAME/rso-projekt:recommender-api-rso ./recommender/
  - docker build -t $DOCKER_USERNAME/rso-projekt:rating-api-rso ./rating/
  - docker build -t $DOCKER_USERNAME/rso-projekt:friends-api-rso ./friends/
  - docker build -t $DOCKER_USERNAME/rso-projekt:subscribe-api-rso ./subscribe/
  - docker build -t $DOCKER_USERNAME/rso-projekt:demo-rso ./demo/




after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/rso-projekt:customers-api-rso
  - docker push $DOCKER_USERNAME/rso-projekt:orders-api-rso
  - docker push $DOCKER_USERNAME/rso-projekt:video-api-rso
  - docker push $DOCKER_USERNAME/rso-projekt:playlists-api-rso
  - docker push $DOCKER_USERNAME/rso-projekt:recommender-api-rso
  - docker push $DOCKER_USERNAME/rso-projekt:rating-api-rso
  - docker push $DOCKER_USERNAME/rso-projekt:friends-api-rso
  - docker push $DOCKER_USERNAME/rso-projekt:subscribe-api-rso
  - docker push $DOCKER_USERNAME/rso-projekt:demo-rso



