kumuluzee:
  name: order-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/OrdersDS
      connection-url: jdbc:postgresql://172.17.0.1:5433/order
      username: postgres
      password: postgres
      max-pool-size: 20