kumuluzee:
  name: video-service
  env:
    name: dev
  version: 1.0.0
  #debug: true
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/VideoDS
      connection-url: jdbc:postgresql://172.17.0.1:5432/customer
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/VideoDS
        username: postgres
        password: postgres

