apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-order-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
      - image: postgres:latest
        name: postgres-order
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: order

        ports:
        - containerPort: 5432
          name: server
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: postgres-order
spec:
  type: NodePort
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-order